package com.hashmap.service;

public enum Status {
    AMOUNT_ADDED,AMOUNT_NOT_ADDED,AUCTION_ADDED,
    AUCTION_NOT_ADDED,USER_ADDED,USER_NOT_ADDED,
    BID_ADDED,BID_NOT_ADDED,PAYMENT_SUCCESSFUL, PAYMENT_NOT_SUCCESSFUL,
    NOT_SUFFICIENTBALANCE,SUFFICIENT_BALANCE;
}
